admin_entity:
    prefix: /{entityName}
    resource: administration/entity.yml
    requirements:
        entityName: category

admin_category:
    prefix: /category
    resource: administration/category.yml

admin_index:
    path: /
    defaults:
        _controller: AppBundle:Administration\Admin:index
    methods: ['GET']
