admin_entity:
    prefix: /{entityName}
    resource: administration/entity.yml
    requirements:
        entityName: category|post

admin_index:
    path: /
    defaults:
        _controller: AppBundle:Administration\Admin:index
    methods: ['GET']
